### ISSUE TITLE
DB design

### ISSUE THREAD

**Issue by teshi24** [Moeby/FlatsharePlanner#14]
Create diagram with mysql workbench. 

Tables to be created:
- User
    - email (unique)
    - username (unique)
    - password
    - group_fk
    - removal_date
- Group  
    - name (not unique)
    - removal_date
- CalendarItem
    - group_fk
    - category (Enum)
    - description (Text)
    - repeatable (Enum) 
    - start_datetime
    - end_datetime
    - assignee (User)
- RepeatableEventException
    - calendar_item_fk
    - start_datetime
    - end_datetime
    - skipped (Boolean)
- ShoppingItem
    - name (Text)
    - bought (boolean, 0 = not assigned, 1 = assigned. If marked as bought --> delete)

**Comment by ThothHermes** [comment]
Create ERD in MySQL Workbench
