### ISSUE TITLE
DB Connection

### ISSUE THREAD

**Issue by Moeby** [Moeby/FlatsharePlanner#43]
- Create database (Cyon) from the [ERD](https://github.com/Moeby/FlatsharePlanner/issues/14)
- Add MYSQL connector library 
- Create connection class [idea](https://github.com/Moeby/FlatsharePlanner/issues/15)
- DB config

**Comment by teshi24** [comment]
**new Prio 13**
effort underestimated
Reasons
- library integration causes a lot of effort
- unknown gradle issues appeared
