### ISSUE TITLE
Implement DAO classes

### ISSUE THREAD

**Issue by Moeby** [Moeby/FlatsharePlanner#44]
One class per table
should finally work --> Maybe problem with open connections
### User
- [x] insert
- [x] selectByUsername
- [x] selectByEmail (Empty method, to be implemented later)
- [x] selectAllByGroupId
- [x] updateGroup (to remove / add a user to a (new) group)
- [x] remove (update that inserts the removal date)
- [x] reactivate (to be implemented later) 
### Group
- [x] insert
- [x] selectById
- [x] remove (update that inserts the removal date)
- [x] reactivate (to be implemented later)
### Shopping Item
- [x] insert 
- [x] selectAllByGroupId
- [x] updateBought
- [x] delete
### Calendar Item
- [x] insert
- [x] selectById
- [x] selectAllByGroupId
- [x] update
- [x] delete (delete exceptions as well)
### Repeatable Event Exception
- [x] insert
- [x] selectByCalendarItem
- [x] update
- [x] delete 
- [x] deleteAllByCalendarItem
### Event Category
- [x] selectById
- [x] selectAll

**Comment by teshi24** [comment]
### New Methods added after first analysis
#### User
- updateGroup (to remove / add a user to a (new) group) --> causes db change
- reactivate (to be implemented later) 
#### Group
- reactivate (to be implemented later)
#### ShoppingItem
- updateBought (required to be able to mark items)
#### RepEventException
- deleteAllByCalendarItem

**Comment by teshi24** [comment]
### Questions
- Will we work with transactions?
  #41 and #43 are also important here
  --> 8.12.17 @teshi24 and @Moeby decided: No, to much effort for our project.

- Should a user be able to update a shopping item?
  --> if yes, add update method and userstory
  --> we decided not to enter this feature

**Comment by teshi24** [comment]
Checked Methods are implemented but not tested yet.
Waiting on DataClasses and Connection for that.

**Comment by teshi24** [comment]
### Testing
for proper testing
#### SetUp
for each table (except EventCategory!!)
``` sql
DELETE FROM rep_event_exception;
DELETE FROM calendar_item;
DELETE FROM shopping_item;
DELETE FROM moebych_Flattie.user;
DELETE FROM moebych_Flattie.group;

ALTER TABLE rep_event_exception AUTO_INCREMENT=1;
ALTER TABLE calendar_item AUTO_INCREMENT=1;
ALTER TABLE shopping_item AUTO_INCREMENT=1;
ALTER TABLE moebych_Flattie.user AUTO_INCREMENT=1;
ALTER TABLE moebych_Flattie.group AUTO_INCREMENT=1;
```
#### Order test methods
table order
- group
- user
- shopping_item
- calendar_item
- rep_event_exception

do same sort of method for all tables before changing sort of methods
- inserts
- selects
- updates
- selects after updates
- deletes / removals
- selects after removals
#### After testing
- clear db again (see SetUp)

**Comment by matalie** [comment]
Test device: Nexus 5x Android 6.0.1 --> APK26

- [x] God implementation style
- [x] FactoryPattern implemented

- [x] all user classes are implemented
- [x] alle dao classes are implemented

- [x] dao-test are working (if DB is empty)
- [x] registration is working
- [x] add calendar entry is working

- [x] login is working
- [x] good comments
- [x] checkstyle is implemented
