### ISSUE TITLE
Registration implementation

### ISSUE THREAD

**Issue by Moeby** [Moeby/FlatsharePlanner#56]
- insert into database
- Password hashing (db adjustment might be needed)
- username verification --> -200 code  (maybe show message?)
- redirect to calendar

**UserStory**
#16 Register US1

**Comment by ThothHermes** [comment]
__Review and Tasting Information__
Test device: Nexus 5x Android 7.0.1 --> APK25
Files: SignupActivity.java, SignupController.java

- [x] God implementation style
- [x] God implementation style

- [x] registration is working
- [x] good comments
- [x] checkstyle is implemented
