### ISSUE TITLE
Login implementation

### ISSUE THREAD

**Issue by matalie** [Moeby/FlatsharePlanner#57]
- check password/username
- select by username
- redirect to calendar

**UserStory**
#17 Login US2

**Comment by teshi24** [comment]
### Review
Nice design with controller :)

Test device: Samsung S5 Android 6.0.1 --> APK 23
#### working
- correct entries: is working
- wrong password: Errormessage 'password
- singup occures

#### issue
- no internet: Errormessage 'Email adress not found.' --> better message would be that there is no internet
- wrong username: Errormessage 'Email adress not found.'

#### ToDo
- [x] add check if internet is enabled (have a look into [AppQuest](https://github.com/teshi24/AppQuest/tree/master/TreasureHunt/app/src/main/java/com/appquest/brudinne/treasurehunt))
- [x] change errormessage to smt more general (e.g. user not found)

**Comment by Moeby** [comment]
Check for internet connection added in a new class. thx for the review! :)
