### ISSUE TITLE
Add Calendar Entry implementation

### ISSUE THREAD

**Issue by ThothHermes** [Moeby/FlatsharePlanner#61]
- implement functionality of creating a calendar entry (add_calendar_entry.xml)
- dummy id for group (id = 1)

**UserStories**
#26 Create Calendar Entry US11
#34 Categorize Calendar Entry Categorize Calendar Entry US19
#35 AssignCalendar Entry US20

**Comment by matalie** [comment]
Very nice date- and timepicker implementation!

Test device: Nexus 5x Android 6.0.1 --> APK26

Working: 
- Insert calendar entry in DB with chosen values
- Set chosen date in datepicker

TODO:
- [ ] implement group object (as soon as group-identification is possible)
